services:
    api_key_user_provider:
        class: MobileBundle\Security\ApiKeyUserProvider
        calls:
         - [getEntityManager, [doctrine.orm.entity_manager]]
    apikey_authenticator:
        class:  MobileBundle\Security\ApiKeyAuthenticator
        public: false
