<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimRepository extends EntityRepository
{
    public function findRecent($max)
    {
         return $this->createQueryBuilder('c')
                 ->orderBy('c.createdAt', 'DESC')
                 ->getQuery()
                 ->setMaxResults($max)
                 ->getResult();
    }
}
