app_resolution:
    resource: "@AppBundle/Controller/ResolutionController.php"
    type:     annotation

app_location:
    resource: "@AppBundle/Controller/LocationController.php"
    type:     annotation

app_resolution:
    resource: "@AppBundle/Controller/ResolutionController.php"
    type:     annotation

app_location:
    resource: "@AppBundle/Controller/LocationController.php"
    type:     annotation

app_authority:
    resource: "@AppBundle/Controller/AuthorityController.php"
    type:     annotation

app_service_location:
    resource: "@AppBundle/Controller/ServiceLocationController.php"
    type:     annotation

mobile:
    resource: "@MobileBundle/Controller/"
    type:     annotation
    prefix:   /mobile
categories:
    resource:   "@MobileBundle/Controller/CategoriesController.php"
    type:   rest
    prefix: /mobile
claims:
    resource:   "@MobileBundle/Controller/ClaimController.php"
    type:   rest
    prefix: /mobile
media:
    resource:   "@MobileBundle/Controller/MediaController.php"
    type:   rest
    prefix: /mobile
location:
    resource:   "@MobileBundle/Controller/LocationController.php"
    type:   rest
    prefix: /mobile    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
