front:
    resource: "@AppBundle/Resources/config/routing/routing.yml"
    prefix:   /front
front_ajax:
    resource: "@AppBundle/Resources/config/routing/routing_ajax.yml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
mobile:
    resource: "@MobileBundle/Controller/"
    type:     annotation
    prefix:   /mobile
categories:
    resource:   "@MobileBundle/Controller/CategoriesController.php"
    type:   rest
    prefix: /mobile
claims:
    resource:   "@MobileBundle/Controller/ClaimController.php"
    type:   rest
    prefix: /mobile
media:
    resource:   "@MobileBundle/Controller/MediaController.php"
    type:   rest
    prefix: /mobile
location:
    resource:   "@MobileBundle/Controller/LocationController.php"
    type:   rest
    prefix: /mobile    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
