app_resolution:
  resource: "@AppBundle/Controller/ResolutionController.php"
  type:     annotation

app_location:
  resource: "@AppBundle/Controller/LocationController.php"
  type:     annotation

app_resolution:
  resource: "@AppBundle/Controller/ResolutionController.php"
  type:     annotation

app_location:
  resource: "@AppBundle/Controller/LocationController.php"
  type:     annotation

app_authority:
  resource: "@AppBundle/Controller/AuthorityController.php"
  type:     annotation

app_service_location:
  resource: "@AppBundle/Controller/ServiceLocationController.php"
  type:     annotation