AppBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        title:
            expose: true
        description:
            expose: true
        claims:
            expose: true
        image:
            expose: true
